- project:
    name: ceph-ansible-nightly-jewel
    release:
      - jewel
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - docker_cluster_collocation
      - update_docker_cluster
      - switch_to_containers
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
      - ooo_collocation
    ceph_ansible_branch:
      - stable-3.0
      - stable-3.1
    jobs:
      - 'ceph-ansible-nightly-{release}-{ceph_ansible_branch}-{scenario}'

- project:
    name: ceph-ansible-nightly-stable3.0
    release:
      - luminous
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - docker_cluster_collocation
      - update_docker_cluster
      - switch_to_containers
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - bluestore_osds_non_container
      - bluestore_osds_container
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
      - purge_bluestore_osds_container
      - purge_bluestore_osds_non_container
      - ooo_collocation
    ceph_ansible_branch:
      - stable-3.0
    jobs:
        - 'ceph-ansible-nightly-{release}-{ceph_ansible_branch}-{scenario}'

- project:
    name: ceph-ansible-nightly-stable3.1
    release:
      - luminous
      - mimic
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - lvm_osds
      - purge_lvm_osds
      - docker_cluster_collocation
      - update_docker_cluster
      - switch_to_containers
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - bluestore_osds_non_container
      - bluestore_osds_container
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
      - purge_bluestore_osds_container
      - purge_bluestore_osds_non_container
      - ooo_collocation
    ceph_ansible_branch:
      - stable-3.1
    jobs:
        - 'ceph-ansible-nightly-{release}-{ceph_ansible_branch}-{scenario}'

- project:
    name: ceph-ansible-nightly-master
    release:
      - dev
    scenario:
      - centos7_cluster
      - xenial_cluster
      - docker_cluster
      - update_cluster
      - lvm_osds
      - purge_lvm_osds
      - docker_cluster_collocation
      - update_docker_cluster
      - switch_to_containers
      - shrink_mon
      - shrink_mon_container
      - shrink_osd
      - shrink_osd_container
      - bluestore_osds_non_container
      - bluestore_osds_container
      - filestore_osds_non_container
      - filestore_osds_container
      - purge_cluster_container
      - purge_cluster_non_container
      - purge_filestore_osds_container
      - purge_filestore_osds_non_container
      - purge_bluestore_osds_container
      - purge_bluestore_osds_non_container
      - ooo_collocation
    ceph_ansible_branch:
      - master
    jobs:
        - 'ceph-ansible-nightly-{release}-{ceph_ansible_branch}-{scenario}'

- job-template:
    name: 'ceph-ansible-nightly-{release}-{ceph_ansible_branch}-{scenario}'
    node: vagrant&&libvirt&&centos7
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Nightly [{release}-{ceph_ansible_branch}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: CEPH_ANSIBLE_BRANCH
          description: "The ceph-ansible branch (or tag) to test"
          default: "{ceph_ansible_branch}"

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - $CEPH_ANSIBLE_BRANCH
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            RELEASE={release}
            CEPH_ANSIBLE_BRANCH={ceph_ansible_branch}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false
